### ISSUE TITLE
TPA00 - wlan-extcap - Test wlan-extcap still operation from a Mac/Wireshark machine

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#56]
plugin for Wireshark on Mac that allows WLAN Pi to be used as remote capture device (also good for Windows if Python installed on Windows machine)

**Comment by adriangranados** [comment]
Same as the Windows version, it needed to adjust the paths to iw, ip, etc. However, instead of creating a version 2 of the script, I removed the use of the absolute paths, so instead of using **/sbin/iw** I just use **iw**. Not using absolute paths seems ok, since these commands are in the system path for sudoers.

The same changes to /etc/sudoers.d/wlanpidump as specified in issue #57 are still required.
