### ISSUE TITLE
TPA30 - WIFiExplorer - Test WFE on Mac can still access WLAN Pi as data source

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/v2-migration-docs#59]

**Comment by wifinigel** [comment]
Asked Helge if he can look at this.

**Comment by adriangranados** [comment]
I can test it.

**Comment by adriangranados** [comment]
The latest version of the sensor script works fine. However, the ability to auto-detect the WLAN Pi as an "external adapter" using the OTG connection doesn't work anymore because the current version of WiFi Explorer Pro is looking for 192.168.42.1. I'll change WiFi Explorer Pro to look for 169.254.42.1 as well. And the other thing is the startup script. I'll work on that.

**Comment by jolla** [comment]
Sounds good, we are still testing the waters using a link-local address, but it would be a good idea to add both.

Thank you,
Jerry Olla

**Comment by adriangranados** [comment]
Tested it on latest image. There was an issue with Scapy (on the script side) that's been corrected. Will test again when the fix is made available in the next build.

**Comment by adriangranados** [comment]
Verified as working in the latest image. Closing.
